# Generated by Django 6.0.4 on 2026-04-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='travel_pics/')),
                ('small_image', models.ImageField(upload_to='travel_pics/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
